name: project_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - accelerate=1.10.0
  - aiohttp=3.12.15
  - annotated-types=0.7.0
  - asttokens=3.0.0
  - async-timeout=5.0.1
  - attrs=25.3.0
  - certifi=2025.8.3
  - charset-normalizer=3.4.3
  - click=8.1.8
  - colorama=0.4.6
  - datasets=2.19.0
  - debugpy=1.8.16
  - decorator=5.2.1
  - diffusers=0.34.0
  - dill=0.3.8
  - exceptiongroup=1.3.0
  - filelock=3.19.1
  - frozenlist=1.7.0
  - fsspec=2024.3.1
  - gitdb=4.0.12
  - gitpython=3.1.45
  - idna=3.10
  - ipykernel=6.30.1
  - ipython=8.18.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - matplotlib-inline=0.1.7
  - mpmath=1.3.0
  - multiprocess=0.70.16
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - ninja=1.13.0
  - numpy=1.26.*
  - packaging=25.0
  - pandas=2.3.1
  - parso=0.8.4
  - peft=0.17.0
  - pillow=11.3.0
  - platformdirs=4.3.8
  - prompt_toolkit=3.0.51
  - psutil=7.0.0
  - pyarrow=21.0.0
  - pydantic=2.11.7
  - pygments=2.19.2
  - python-dateutil=2.9.0
  - pytz=2025.2
  - pywin32=311
  - pyyaml=6.0.2
  - pyzmq=27.0.1
  - regex=2025.7.34
  - requests=2.32.4
  - safetensors=0.6.2
  - scipy=1.13.1
  - sentry-sdk=2.35.0
  - six=1.17.0
  - sympy=1.13.1
  - tokenizers=0.21.4
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - transformers=4.55.2
  - typing_extensions=4.14.1
  - urllib3=2.5.0
  - wandb=0.21.1
  - wcwidth=0.2.13
  - zipp=3.23.0
  - pip
  - pip:
      - xxhash==3.5.0
      - tzdata==2025.2
      - protobuf==6.32.0
      - stack-data==0.6.3
      - huggingface-hub==0.34.4
      - multidict==6.6.4
      - aiohappyeyeballs==2.6.1
      - comm==0.2.3
      - eval_type_backport==0.2.2
      - executing==2.2.0
      - hf-xet==1.1.7
      - pure_eval==0.2.3
      - pyarrow-hotfix==0.7
      - pydantic_core==2.33.2
      - propcache==0.3.2
      - smmap==5.0.2
      - xformers==0.0.27.post2
      - bitsandbytes==0.43.1
      - typing-inspection==0.4.1
